apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hadoop
  name: hadoop
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hadoop
    spec:
      containers:
      - image: docker.io/jayunit100/presto-hadoop-hive
        name: hadoop-master
        resources: {}
        volumeMounts:
        - mountPath: /etc/hadoop/conf/
          name: hadoop-cm
      hostname: hadoop-master
      restartPolicy: Always
      volumes:
      - name: hadoop-cm
        configMap:
          name: hadoop-cm
status: {}
