apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hadoop
  name: hadoop
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hadoop
    spec:
      containers:
      - image: prestodb/cdh5.13-hive:latest
        name: hadoop-master
        resources: {}
        volumeMounts:
        - mountPath: /etc/hadoop/conf/core-site.xml
          name: hadoop-claim0
        - mountPath: /usr/lib/hive/lib/json-udf-1.3.8-jar-with-dependencies.jar
          name: hadoop-claim1
        - mountPath: /usr/lib/hive/lib/json-serde-1.3.8-jar-with-dependencies.jar
          name: hadoop-claim2
      hostname: hadoop-master
      restartPolicy: Always
      volumes:
      - name: hadoop-claim0
        persistentVolumeClaim:
          claimName: hadoop-claim0
      - name: hadoop-claim1
        persistentVolumeClaim:
          claimName: hadoop-claim1
      - name: hadoop-claim2
        persistentVolumeClaim:
          claimName: hadoop-claim2
status: {}
