apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "hbase.name" . }}-hbase-master
  labels:
    app: {{ template "hadoop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hbase-master
spec:
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: hbase-master
  minAvailable: 1 # FIXME: HA?