apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    presto: worker
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        presto: worker
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: prestocfg
        image: johandry/presto
        livenessProbe:
          exec:
            command:
            - /etc/init.d/presto status | grep -q 'Running as'
          failureThreshold: 3
          periodSeconds: 300
          timeoutSeconds: 10
        name: worker
        ports:
        - containerPort: 8080
      restartPolicy: Always
